Feature disable motion magic
Mechanical-Advantage/RobotCode2024 pull request #11
Opened 2024-02-14 01:13 UTC by suryatho

Moved arm motion profile and the feedforward model into the subsystem. The IO layer only has to deal with controlling to the current setpoint.

2024-02-14 01:41 UTC, jwbonner requested changes

2024-02-14 01:41 UTC, jwbonner commented on build.gradle
> +//compileJava.finalizedBy generateDriveTrajectories
This can still be enabled on main

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/Constants.java
> +  private static RobotType robotType = RobotType.SIMBOT;
Can stay as DEVBOT, not related to the changes

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +          superstructure = new Superstructure(arm);
This is created lower down already since it's the same for all robots

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +    //    autoChooser.addOption("Drive Straight", autoCommands.driveStraight());
Is there a reason this is commented out?

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +        .onTrue(rollers.feedShooter().withTimeout(1.0).withName("Shoot"));
This will not automatically cancel aiming when the shot finishes (or ensure that aiming is continued while the shot is being fired). Is this an intentional change?

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +                .alongWith(rollers.floorIntake().onlyIf(superstructure::atGoal))
This is only evaluated once when the command starts. It seems like you'd want to wait until the superstructure is at the goal and then start the rollers.

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +                .alongWith(rollers.ejectFloor().onlyIf(superstructure::atGoal))
Ditto

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/flywheels/Flywheels.java
> +  @Getter @Setter private Goal goal = Goal.IDLING;
Making this a setter means you can set it publicly, but the public interface should be through the commands

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/flywheels/Flywheels.java
> +  private boolean characterizing = false;
Are these variables used anywhere?

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/flywheels/Flywheels.java
> +  public Command stop() {
This is the default behavior when disabled. Is there a reason for an explicit command?

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/flywheels/Flywheels.java
> +  public Command idle() {
Same, this doesn't need to be explicit when all of the commands already set the idle goal

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/flywheels/Flywheels.java
> +    System.out.println("[Init] Creating Shooter");
We may want to set this up, but this only in one subsystem. Let's hold off for now

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/GenericRollerSystemIOSim.java
> +  private final FlywheelSim sim;
This can be a `DCMotorSim` so you don't need to manually integrate position

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/flywheels/Flywheels.java
> +    setDefaultCommand(idle());
See below about an explicit idle command

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/Rollers.java
> +    setDefaultCommand(idle());
Same as flywheel about explicit idle command

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/Rollers.java
> +    switch (goal) {
Why is the behavior when disabled removed? Commands don't run when disabled. Alternatively the default command could be set up to run when disabled

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/Rollers.java
> +  public Command idle() {
Same as flywheel about explicit idle command

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/feeder/Feeder.java
>    public enum Goal implements GenericRollerSystem.VoltageGoal {
`GenericRollerSystem.VoltageGoal` is inconsistent with the change you made to the other two. I would include it in all or remove it from all

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/Superstructure.java
> +  @Getter @Setter private SystemState goal = SystemState.STOWING;
Same as flywheels, you don't want `@Setter` because it makes it publicly accessible

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/Superstructure.java
> +    currentState = goal; // Will change soon
Same as before, reason for removing the disabled behavior?

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/Superstructure.java
> +    currentState = goal; // Will change soon
(Particularly with the removal of the default command too)

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/Superstructure.java
> +  public Command stow() {
Same as other subsystems, no need for an explicit idle command

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/Arm.java
> +public class Arm extends SubsystemBase {
Arm should not be a subsystem because it is composed in the superstructure

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/ArmVisualizer.java
> +            armOrigin.getX(), 0.0, armOrigin.getY(), new Rotation3d(0.0, angle.getRadians(), 0.0));
Did you test this? The pitch direction is the opposite of how we usually measure arm angles.

2024-02-14 01:41 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/Rollers.java
> +    switch (goal) {
(Make sure to test that, not totally sure if that works)

2024-02-14 03:13 UTC, suryatho commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +    //    autoChooser.addOption("Drive Straight", autoCommands.driveStraight());
I didn't have the docker container running so I wanted I stopped the autos from building to avoid an error

2024-02-14 03:15 UTC, suryatho commented on src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/Superstructure.java
> +  @Getter @Setter private SystemState goal = SystemState.STOWING;
ok

2024-02-14 03:17 UTC, suryatho commented on src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/ArmVisualizer.java
> +            armOrigin.getX(), 0.0, armOrigin.getY(), new Rotation3d(0.0, angle.getRadians(), 0.0));
No I didn't test that, it probably needs to be negated

2024-02-14 03:17 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +    //    autoChooser.addOption("Drive Straight", autoCommands.driveStraight());
That’s fine, just make sure not to commit temporary changes

2024-02-14 03:17 UTC, suryatho commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +        .onTrue(rollers.feedShooter().withTimeout(1.0).withName("Shoot"));
Technically the driver still has to be aiming for the readyToShoot trigger to be true, but other than that I don't think that the shot should necessarily cancel the aiming because feeding for 1 second is sometimes not enough to even push the note into the flywheels, so the driver should still be aiming.

2024-02-14 03:22 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +        .onTrue(rollers.feedShooter().withTimeout(1.0).withName("Shoot"));
Sure, though you want to account for the case where the aiming is stopped before the shot is completed. Maybe using the old behavior but continuing to shoot for as long as the button is pressed (with a minimum time) would solve that issue.

2024-02-14 03:29 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +        .onTrue(rollers.feedShooter().withTimeout(1.0).withName("Shoot"));
I think it would be something like: parallel(wait 1 sec, wait until trigger released).deadlineWith(rollers shoot, aim superstructure, aim flywheels)

2024-02-14 15:18 UTC, jwbonner commented
Looks good, just make sure to fix those last couple of issues and we can get this merged.

2024-02-15 22:12 UTC, jwbonner requested changes

2024-02-15 22:12 UTC, jwbonner commented on Robot_MA24B/config.json
Is there supposed to be a model file?

2024-02-15 22:12 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/Arm.java
>    public boolean atSetpoint() {
Didn't notice this before, but this can use the setpoint and goal instead of a tolerance similar to the new flywheel logic (same reasoning, blocking all robot actions due to a tolerance issue is undesirable)

2024-02-15 23:35 UTC, jwbonner commented
I pushed a couple of fixes for the model, so it's just the `atSetpoint` logic that needs to be changed.

2024-02-16 01:18 UTC, jwbonner requested changes

2024-02-16 01:18 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/arm/Arm.java
>          <= Units.degreesToRadians(toleranceDegrees.get());
This is an improvement, but what I meant is that you can just check `setpointState.position == goal.getRads()` (or use a small tolerance like `1e-3`).

2024-02-16 02:11 UTC, jwbonner approved these changes

2024-02-16 02:11 UTC, merged