Use supplyCurrentAmps and torqueCurrentAmps for all inputs
Mechanical-Advantage/RobotCode2024 pull request #111
Opened 2024-02-24 20:45 UTC by suryatho

2024-02-26 03:00 UTC, camearle20 requested changes
Change this in ArmIO as well?

2024-02-26 23:35 UTC, jwbonner requested changes

2024-02-26 23:35 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/rollers/GenericRollerSystemIOKrakenFOC.java
> +        BaseStatusSignal.refreshAll(position, velocity, appliedVoltage, supplyCurrent).isOK();
Need to refresh torque current

2024-02-27 02:08 UTC, jwbonner approved these changes

2024-02-27 02:13 UTC, merged