Set turn motor position to absolute position at start up
Mechanical-Advantage/RobotCode2024 pull request #14
Opened 2024-02-14 04:30 UTC by suryatho

- Use pre-defined members for control rather than creating new control request each cycle 
- Use feedforward input from module always
- Run drive and turn with amps
- Make every control request one shot
- Make alerts for drive and turn disconnected
- Rename methods in ModuleIO

2024-02-14 05:05 UTC, jwbonner requested changes

2024-02-14 05:05 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/drive/ModuleIOKrakenFOC.java
> +            == StatusCode.OK;
Ditto

2024-02-15 22:23 UTC, jwbonner commented
I think the only thing left is fixing the robot in Constants.

2024-02-16 01:40 UTC, jwbonner requested changes

2024-02-16 01:40 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/drive/Drive.java
> +      if (brakeModeEnabled) {
(We discussed this)

2024-02-16 02:09 UTC, jwbonner requested changes

2024-02-16 02:09 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/drive/Drive.java
> +      if (EqualsUtil.epsilonEquals(
It looks like this doesn't reset the timer if the velocity rises above the threshold, and it also never hits the timer check if the robot is stopped. This code may be useful for reference: https://github.com/Mechanical-Advantage/RobotCode2023/blob/main/src/main/java/org/littletonrobotics/frc2023/subsystems/drive/Drive.java#L247

2024-02-16 18:07 UTC, suryatho commented on src/main/java/org/littletonrobotics/frc2024/subsystems/drive/Drive.java
> +      if (EqualsUtil.epsilonEquals(
fixed in latest

2024-02-17 01:32 UTC, jwbonner requested changes

2024-02-17 01:32 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/drive/Drive.java
> +  @Getter(onMethod_ = @AutoLogOutput(key = "Drive/BrakeModeEnabled"))
This is very minor, but you can just add the `@AutoLogOutput` annotation normally since it works on fields

2024-02-17 04:30 UTC, jwbonner approved these changes

2024-02-17 04:36 UTC, jwbonner approved these changes

2024-02-17 04:37 UTC, merged