Use interpolating tree map for calculating arm angle
Mechanical-Advantage/RobotCode2024 pull request #16
Opened 2024-02-15 04:08 UTC by suryatho

2024-02-15 22:25 UTC, jwbonner submitted a review, later dismissed
This looks good for now, though we should chat about whether the interpolation tables should be separated once there are multiple.

2024-02-15 23:24 UTC, camearle20 requested changes

2024-02-15 23:24 UTC, camearle20 commented on src/main/java/org/littletonrobotics/frc2024/RobotState.java
> +  private static final LoggedTunableNumber shotHeightCompensation =
This is unused now, but we probably should have some kind of angular compensation that is adjustable by the driver at some point either on the dashboard or with up/down buttons. In this case it probably shouldn't be tunable number but an actual value that has accessors

2024-02-16 00:59 UTC, jwbonner approved these changes

2024-02-16 01:00 UTC, merged