Use LinearProfile for flywheels
Mechanical-Advantage/RobotCode2024 pull request #17
Opened 2024-02-15 05:25 UTC by suryatho

Switched to using a linear profile to track setpoint and monitor check if flywheels are at the goal rpm. Tuned the sim gains to rev in ~1 sec.

2024-02-15 22:37 UTC, jwbonner requested changes

2024-02-15 22:37 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/flywheels/Flywheels.java
> +    leftProfile = new LinearProfile(maxAcceleration.get(), 0.02);
This can use the loop time constant

2024-02-15 22:37 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/flywheels/Flywheels.java
> +  public boolean atGoal() {
Instead of using a tolerance, this should just check whether the setpoint equals the goal.

2024-02-15 22:37 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/flywheels/Flywheels.java
> +    leftProfile.setGoal(goal.getLeftGoal(), inputs.leftVelocityRpm);
I think you'll probably want to update the profile goals in periodic, since they're double suppliers that aren't necessarily constant.

2024-02-16 02:24 UTC, jwbonner approved these changes

2024-02-16 02:27 UTC, jwbonner requested changes
Fix issue with epsilon and idle mode with testing in sim (as discussed)

2024-02-17 00:21 UTC, camearle20 approved these changes

2024-02-17 00:58 UTC, camearle20 approved these changes

2024-02-17 00:59 UTC, merged