Clean up rumble commands
Mechanical-Advantage/RobotCode2024 pull request #173
Opened 2024-03-08 00:39 UTC by suryatho

2024-03-09 21:47 UTC, jwbonner requested changes

2024-03-09 21:47 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +                        .withTimeout(0.9) // Rumble three times
pls fix thx

2024-03-09 22:17 UTC, suryatho commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +                        .withTimeout(0.9) // Rumble three times
👍

2024-03-12 01:36 UTC, jwbonner requested changes

2024-03-12 01:36 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +  private Command controllerRumbleCommand(boolean useRightRumble, boolean rumbleOperator) {
Every instance where this method is called passes the same arguments...

2024-03-13 01:42 UTC, jwbonner requested changes

2024-03-13 01:42 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +    driver.a().and(readyToShoot).whileTrue(controllerRumbleCommand());
This line seems to appear twice...

2024-03-13 03:41 UTC, suryatho commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +    driver.a().and(readyToShoot).whileTrue(controllerRumbleCommand());
fixed

2024-03-14 21:29 UTC, jwbonner approved these changes

2024-03-14 21:29 UTC, merged