Driver controls for scoring
Mechanical-Advantage/RobotCode2024 pull request #195
Opened 2024-03-12 01:09 UTC by suryatho

Use right trigger for pooping
Amp without autoDrive turns robot to 90

2024-03-13 01:43 UTC, jwbonner requested changes

2024-03-13 01:43 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +                              }
This should use the same rotation tolerance as the auto drive

2024-03-13 03:40 UTC, suryatho commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +                              }
fix

2024-03-14 01:31 UTC, jwbonner approved these changes

2024-03-14 01:33 UTC, merged