NECMP Changes
Mechanical-Advantage/RobotCode2024 pull request #252
Opened 2024-04-08 22:59 UTC by camearle20

2024-04-08 23:10 UTC, jwbonner requested changes

2024-04-08 23:10 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotState.java
> +  private static final double autoFarShotCompensationDegrees = 0.6;
Should this be reset to 0° or keep it at 0.6°?

2024-04-09 23:52 UTC, suryatho commented on src/main/java/org/littletonrobotics/frc2024/RobotState.java
> +  private static final double autoFarShotCompensationDegrees = 0.6;
I think we just keep it at 0

2024-04-09 23:53 UTC, suryatho approved these changes

2024-04-10 23:40 UTC, jwbonner approved these changes

2024-04-11 00:47 UTC, merged