Add NoteVisualizer
Mechanical-Advantage/RobotCode2024 pull request #69
Opened 2024-02-20 00:53 UTC by suryatho

2024-02-20 01:28 UTC, jwbonner requested changes

2024-02-20 01:28 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/util/NoteVisualizer.java
> +  private static final double ampSpeed = 4.0;
This is unused

2024-02-20 01:28 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/util/NoteVisualizer.java
> +  public static void resetAutoNotes() {
It looks like this doesn't clear the existing list of notes

2024-02-20 02:16 UTC, jwbonner requested changes

2024-02-20 02:16 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +    // Set supplies for NoteVisualizer
*suppliers

2024-02-20 02:16 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +    NoteVisualizer.setArmAngleSupplier(arm::getSetpoint);
This should probably be the measured position and not the setpoint. You may need to configure it in the arm constructor instead.

2024-02-20 10:01 UTC, suryatho commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +    NoteVisualizer.setArmAngleSupplier(arm::getSetpoint);
fix

2024-02-20 23:35 UTC, jwbonner requested changes

2024-02-20 23:35 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/RobotContainer.java
> +    arm.setArmAngleConsumer(NoteVisualizer::setCurrentArmAngle);
Why is one of these a supplier and one a consumer? I think it would be better for the arm to just set an angle supplier on the NoteVisualizer separately.

2024-02-20 23:35 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/util/NoteVisualizer.java
> +    Logger.recordOutput("NoteVisualizer/HeldNote", getIndexerPose3d());
I think this should use a separate key so that it doesn't conflict with the shot note. It should also be an array which can be explicitly set to empty when not holding a note.

2024-02-21 23:47 UTC, jwbonner requested changes
Other than removing `GenericLinearSlamElevatorIO` I think this looks good

2024-02-21 23:47 UTC, jwbonner commented on src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/GenericLinearSlamElevatorIO.java
I'm pretty sure you didn't mean to commit this

2024-02-22 00:16 UTC, suryatho commented on src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/GenericLinearSlamElevatorIO.java
uh oh 😓

2024-02-22 00:24 UTC, jwbonner approved these changes

2024-02-22 00:25 UTC, merged