Add elevator subsystems
Mechanical-Advantage/RobotCode2024 pull request #92
Opened 2024-02-22 23:56 UTC by suryatho

2024-02-23 00:00 UTC, suryatho commented
Need to test on actual robot

2024-02-23 20:21 UTC, camearle20 requested changes

2024-02-23 20:21 UTC, camearle20 commented on src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/GenericSlamElevator.java
> +    /** Returns either -1 or 1 based on directino of slamming */
direction

2024-02-23 20:21 UTC, camearle20 commented on src/main/java/org/littletonrobotics/frc2024/subsystems/superstructure/GenericSlamElevator.java
> +      double slammingCurrent,
Separate out extending and retracting current since we may want these to be different (climber should pull down harder to climb than it pushes up to get into position)

2024-02-29 16:42 UTC, suryatho commented
Add manual reset superstructure button for operator

2024-03-01 00:54 UTC, jwbonner approved these changes

2024-03-01 00:55 UTC, merged